
# Gem::Specification for Gitviz-0.1.0
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{gitviz}
  s.version = "0.1.0"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [""]
  s.date = %q{2008-04-27}
  s.default_executable = %q{gitviz}
  s.description = %q{}
  s.email = %q{}
  s.executables = ["gitviz"]
  s.extra_rdoc_files = ["bin/gitviz", "CHANGELOG", "lib/gitviz/digraph.rb", "lib/gitviz/errors.rb", "lib/gitviz/git_commands.rb", "lib/gitviz.rb", "LICENSE", "README.markdown"]
  s.files = ["bin/gitviz", "CHANGELOG", "lib/gitviz/digraph.rb", "lib/gitviz/errors.rb", "lib/gitviz/git_commands.rb", "lib/gitviz.rb", "LICENSE", "Manifest", "README.markdown", "spec/gitviz_spec.rb", "spec/spec.opts", "spec/spec_helper.rb", "gitviz.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Gitviz", "--main", "README.markdown"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{gitviz}
  s.rubygems_version = %q{1.0.1}
  s.summary = %q{}
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'echoe'
# Echoe.new('gitviz')#  do |p|
# #   p.author  = "Rein Henrichs"
# #   p.email   = "reinh@reinh.com"
# #   p.summary = "GitViz generates DOT files from git commit graphs for GraphViz and great justice."
# #   p.url     = "http://github.com/reinh/gitviz"
# # end
